[tool.poetry]
name = "flask-python"
version = "0.1.0"
description = ""
authors = ["Daiane Cruz <daianercruz12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask-sqlalchemy = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
